# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54ea625ebc6896fa979b0764e13fa4f5b4a9355fef87644f86998aa19dcdb97b7fa3d569d707670146717327a4d4ff55b742ed5c7b3970619876f603c16167ae

test:
  secret_key_base: 00eba128308085afd32206bb44a93cde7986dd71447a497d23516c86139491b6c8deb9d0c88536863a2a0b4c8b028ff99b5f3379ca042a63ec5a56ef53935b94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
